apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-news
  labels:
    app: fake-news
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fake-news
  template:
    metadata:
      labels:
        app: fake-news
    spec:
      containers:
      - name: fake-news-app
        image: "{{ full_image | default('chrispinmourus/fake-news-app:latest') }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
